In [2]:
import torch
import numpy as np

In [3]:
TENSOR1 = torch.randn(7, 7)
TENSOR2 = torch.randn(1, 7)

In [4]:
torch.matmul(TENSOR1, TENSOR2.T)

tensor([[ 2.2635],
        [ 7.0257],
        [-0.0216],
        [-1.4763],
        [ 1.2434],
        [-5.7276],
        [-5.5159]])

In [5]:
torch.manual_seed(seed=0)
TENSOR1 = torch.randn(7, 7)

torch.manual_seed(seed=0)
TENSOR2 = torch.randn(1, 7)

torch.matmul(TENSOR1, TENSOR2.T)

tensor([[-3.1132],
        [-0.4052],
        [ 2.2938],
        [-4.9556],
        [-0.9954],
        [ 1.9452],
        [ 2.2410]])

In [6]:
torch.cuda.is_available() 

True

In [7]:
torch.cuda.manual_seed_all(1234)
tensor_A = torch.rand(size=(2, 3)).to("cuda")
tensor_B = torch.rand(size=(2, 3)).to("cuda")
print(f"Tensor A:\n{tensor_A}\nDevice: {tensor_A.device}\n")
print(f"Tensor B:\n{tensor_B}\nDevice: {tensor_B.device}")

Tensor A:
tensor([[0.6977, 0.8000, 0.1610],
        [0.2823, 0.6816, 0.9152]], device='cuda:0')
Device: cuda:0

Tensor B:
tensor([[0.3971, 0.8742, 0.4194],
        [0.5529, 0.9527, 0.0362]], device='cuda:0')
Device: cuda:0


In [11]:
res = torch.matmul(tensor_A, tensor_B.T)
res

tensor([[1.0439, 1.1538],
        [1.0918, 0.8386]], device='cuda:0')

In [12]:
torch.max(res), torch.min(res), torch.argmax(res), torch.argmin(res)

(tensor(1.1538, device='cuda:0'),
 tensor(0.8386, device='cuda:0'),
 tensor(1, device='cuda:0'),
 tensor(3, device='cuda:0'))